"""
# ⚠️ DEPRECATED(Phase 2, 评审 #62): 新代码禁止 import——统一从 CommandSpec 读取
cli_tools_registry — 82 个命令行工具的共享注册表（name → java 类名）
====================================================================
FIX(P0-3): 原注册表仅存在于旧入口 bin/tbcli.py，新入口 tbtools tool 不可达
（外部测试 2026-09-19 报告 §3.3）。抽取为共享模块，新旧入口共用：
  - bin/tbcli.py（旧入口）import 本模块
  - tbtools_cli/cli.py ToolGroup（新入口）import 本模块
"""

CLI_TOOLS = {
    "DecodeIlluminaFqPool": "biocjava.bioDoer.Fastq.DecodeIlluminaFqPool",
    "fastaIDAppender": "biocjava.bioIO.FastX.FastaIndex.FastaIDAppender",
    "rpkmCal": "biocjava.bioDoer.ExpressionLevelCalculator.RPKMcalculator",
    "fpkmToTpm": "biocjava.bioDoer.ExpressionLevelCalculator.FPKMtoTPM",
    "tpmCalc": "biocjava.bioDoer.ExpressionLevelCalculator.TPMcalculator",
    "mimicVqsr": "biocjava.bioDoer.GWAS.MimicVqsrCutoffFind",
    "autoMakeBlastDb": "biocjava.bioDoer.BLAST.makeblastdb",
    "autoRemoteBlast": "biocjava.bioDoer.BLAST.remoteblast",
    "GoCompareBar": "biocjava.bioDoer.GeneOntology.Grapher.GoCompare",
    "plotRNAfoldloci": "biocjava.bioDoer.JIGplotToolkit.miRCoverage.PlotRNAfold",
    "getLongestCompleteORF": "biocjava.bioIO.ORF.ORF",
    "ExtractFeaturefromGFF3andGenome": "biocjava.bioIO.GFF.ExtractFeaturefromGFF3andGenome",
    "Fasta36m10toTable": "biocjava.bioIO.FastaAligner.Fasta36m10toTable",
    "FastaIDRenamer": "biocjava.bioIO.FastX.FastaIndex.FastaIDRenamer",
    "FastaIDSimplifier": "biocjava.bioIO.FastX.FastaIndex.FastaIDSimplifier",
    "FastaLongestRepresentater": "biocjava.bioIO.FastX.FastaIndex.FastaLongestRepresentater",
    "FoldStructureStater": "biocjava.bioIO.RNAfold.FoldStructureStater",
    "GXFOverlaper": "biocjava.bioDoer.GXFUtils.GXFOverlaper",
    "NCBITaxonomy": "biocjava.bioWeb.NCBITaxonomy.NCBITaxonomy",
    "OneStepMirGraph": "biocjava.bioIO.RNAfold.OneStepMirGraph",
    "OverlapGeneModels": "biocjava.bioIO.GXF.gxfTree.OverlapGeneModels",
    "PredictMirSTAR": "biocjava.bioIO.RNAfold.PredictMirSTAR",
    "RNAplotAdvance": "biocjava.bioDoer.JIGplotToolkit.miRCoverage.RNAplotAdvance",
    "MIRPrediionResultStat": "biocjava.bioDoer.miRNA.MIRPrediionResultStat",
    "ReciprocalBlast": "biocjava.bioDoer.BLAST.ReciprocalBlast.ReciprocalBlast",
    "RegionGXFOverlapAnnotation": "biocjava.bioDoer.GXFUtils.RegionGXFOverlapAnnotation",
    "TableCast": "biocjava.bioDoer.Table.TableCast",
    "TableColSelector": "biocjava.bioDoer.Table.TableColSelector",
    "TableMelt": "biocjava.bioDoer.Table.TableMelt",
    "downLoadNCBIFasta": "biocjava.bioWeb.DownLoadNCBIFasta",
    "extractFasta": "biocjava.bioDoer.Fasta.ExtractFasta",
    "extractFastaSub": "biocjava.bioDoer.Fasta.ExtractFastaSubseq",
    "keggEnrichment": "biocjava.bioDoer.Kegg.AdvancedForEnrichment.KeggEnrichment",
    "goAnnoPipe": "biocjava.bioDoer.GeneOntology.Annotation.GoAnnoPipe",
    "dnDsCalculate": "biocjava.bioIO.KaKs.DnDsCalculate",
    "ssrMiner": "biocjava.bioIO.FastX.FastaIndex.SSRminer",
    "checkPrimer": "biocjava.bioIO.Primer.CheckPrimer",
    "quickLocateSeqPattern": "biocjava.bioIO.FastX.QuickLocateSeqPattern",
    "blastXmlSummaryTable": "biocjava.bioIO.BlastXml.BlastXMLSummaryTable",
    "emblToFasta": "biocjava.bioIO.Embl.emblToFasta",
    "gbff2gff": "biocjava.bioIO.GBff.gbff2gff",
    "extractGff3Region": "biocjava.bioIO.GFF.ExtractGff3Region",
    "vcfBinCount": "biocjava.bioIO.HTSData.VCF.VCFBINCount",
    "getLongestORF": "biocjava.bioIO.ORF.GetLongestORF",
    "translater": "biocjava.bioIO.ORF.Translater",
    "makeFastaIndex": "biocjava.bioIO.FastX.FastaIndex.MakeFastaIndex",
    "quickSplitFasta": "biocjava.bioIO.FastX.FastaIndex.QuickSpiltFasta",
    "fastaFragmenter": "biocjava.bioIO.FastX.FastaIndex.Fragment.FastaFragmenter",
    "eggNogMapperResult": "biocjava.bioIO.BioSoftPipeServer.eggNogMapperResult",
    "tandemDupFinder": "biocjava.bioIO.BioSoftPipeServer.TandemDupFinder",
    "genePairExpCorr": "biocjava.bioIO.BioSoftPipeServer.GenePairExpCorr",
    "slurmScriptPrepare": "biocjava.bioIO.BioSoftPipeServer.SlurmScriptPrepare",
    "geneExpFilter": "biocjava.bioIO.BioSoftPipeServer.GeneExpFilter",
    "prepareFileFromMCScanXtoTBtools": "biocjava.bioDoer.JIGplotToolkit.Synteny.PrepareFileFromMCScanXtoTBtools",
    "blastXmlToTable": "biocjava.bioIO.BlastXml.BlastXmlToSelfDefinedTable",
    "targetSoPipe": "biocjava.bioDoer.miRNA.TargetSoPipe",
    "target2TablePipe": "biocjava.bioDoer.miRNA.Target2TablePipe",
    "mirIdentifierBasedOnTargetSo": "biocjava.bioDoer.miRNA.MIRidentifierBasedOnTargetSoResult",
    "regionBlast": "biocjava.bioDoer.BLAST.wholeGenomeBlastN.regionBlast",
    "findBestHomologyBatch": "biocjava.bioIO.BioSoftPipeServer.FindBestHomologyBatch",
    "collinearityToRegion": "biocjava.bioDoer.ComparativeGenomics.MCScanX.CollinearityToRegion",
    "pairWiseKaKsCalculator": "biocjava.bioIO.BioSoftPipeServer.PairWiseKaKsCalculator",
    "simpleBatchProcess": "biocjava.bioDoer.Aligner.NeedleMan.SimpleBatchProcess",
    "quickGeneFamilyIdentification": "biocjava.bioDoer.BLAST.ReciprocalBlast.QuickGeneFamilyIdentification",
    "gffCdsPhaseCorrector": "biocjava.bioDoer.GXFUtils.GffCdsPhase.GffCdsPhaseCorrector",
    "parallelMD5Check": "biocjava.bioDoer.FileUtils.ParallelMD5Check",
    "pafRefBaseCoverCalc": "biocjava.bioDoer.JIGplotToolkit.Paf.PafRefBaseCoverCalc",
    "sRNAseqReadLenStat": "biocjava.sRNA.Tools.sRNAseqReadLenStat",
    "sRNAReadTrimmer": "biocjava.sRNA.Tools.sRNAReadTrimmer",
    "sRNAseqAdaperRemover": "biocjava.sRNA.Tools.sRNAseqAdaperRemover",
    "fastqParallelTrimmer": "biocjava.bioDoer.Fastq.FastqParallelTrimmer",
    "fastqParallelSubBest": "biocjava.bioDoer.Fastq.FastqParallelSubBest",
    "fastqAndFasta": "biocjava.bioDoer.LinuxPipe.FastqAndFasta",
    "extractFeatureFromGTF": "biocjava.bioIO.GTF.ExtractFeaturefromGTFandGenome",
    "sRNAseqCollasper": "biocjava.sRNA.Tools.sRNAseqCollasper",
    "generateMotifFromSequences": "biocjava.bioIO.BioSoftPipeServer.MEMEsuiteWrapper.GenerateMotifFromSequences",
    "sRNAseqDeCollasper": "biocjava.sRNA.Tools.sRNAseqDeCollasper",
    "findBestForkerRootTree": "biocjava.bioDoer.JIGplotToolkit.newickParser.FindBestForkerRootTree",
    "statFasta": "biocjava.bioIO.FastX.FastaIndex.QuickStatFasta",
    "goEnrichMerge": "biocjava.bioDoer.JIGplotToolkit.EnrichmentAnalysisGraph.GOEnrichmentMergeBubble",
    "vcfAddID": "biocjava.bioDoer.GWAS.VCFAddID",
    "bigMarkerRandomDesign": "biocjava.bioDoer.markerDesign.BigMarkerRandomDesign"
}
